pipeline
{
agent {
  label 'dockerNode'
}
environment {
  name = "Ravi"
}
parameters {
  string defaultValue: 'Ravi', name: 'FirstName'
}
tools {
  maven 'Maven_3_9'
}
stages{
	
	stage('build'){
		steps{
			sh 'mvn clean package'
			echo "hello $name ${params.FirstName}"
		}
		post {
		  success {
		    archiveArtifacts artifacts: '**/target/*.jar'
  				}
			}
	}
}
}